In [1]:
import array

L = list(range(10))
A = array.array("i", L)
print(f"L:", L)
print(f"A:", A)

L: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
A: array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [6]:
import numpy as np

np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [7]:
np.array([3.14, 4, 2, 3])  # python upcasts if possible when types do not match

array([ 3.14,  4.  ,  2.  ,  3.  ])

In [8]:
np.array([1, 2, 3, 4], dtype="float32")

array([ 1.,  2.,  3.,  4.], dtype=float32)

In [9]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [5]:
import numpy as np

np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
np.ones((3, 5), dtype="float")

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [11]:
np.full((3, 5), 3.14)

array([[ 3.14,  3.14,  3.14,  3.14,  3.14],
       [ 3.14,  3.14,  3.14,  3.14,  3.14],
       [ 3.14,  3.14,  3.14,  3.14,  3.14]])

In [12]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [13]:
np.linspace(0, 1, 5)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ])

In [15]:
np.random.random((3, 3))

array([[ 0.85296888,  0.43556497,  0.04412798],
       [ 0.55791842,  0.48693298,  0.07115575],
       [ 0.10768842,  0.01145473,  0.1548723 ]])

In [16]:
# create a 3x3 array of normally distributed random values with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[-1.64211998,  1.2102595 ,  1.13388717],
       [-0.60263457, -0.6270278 ,  0.57570003],
       [-0.01368519,  0.28587877,  1.30416292]])

In [17]:
np.random.randint(0, 10, (3, 3))  # create a 3x3 array of random integers in the interval (0, 10)

array([[8, 4, 1],
       [4, 8, 0],
       [9, 1, 3]])

In [19]:
# 3x3 identity matrix
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [20]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that memory location
np.empty(3)

array([ 1.,  1.,  1.])

In [21]:
np.zeros(10, dtype="int16")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [22]:
np.zeros(10, dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)