In [1]:
import array

L = list(range(10))
A = array.array("i", L)
print(f"L:", L)
print(f"A:", A)

L: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
A: array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [2]:
import numpy as np

a = np.array([1, 4, 2, 5, 3])
print(f"a:", a)

a: [1 4 2 5 3]


In [3]:
ar = np.array([3.14, 4, 2, 3])
print(f"ar:", ar)  # python upcasts if possible when types do not match

ar: [ 3.14  4.    2.    3.  ]


In [4]:
arr = np.array([1, 2, 3, 4], dtype="float32")
print(f"arr:", arr)

arr: [ 1.  2.  3.  4.]


In [5]:
new_a = np.array([range(i, i + 3) for i in [2, 4, 6]])
print(f"new_a:", new_a)
print()
print(new_a)

new_a: [[2 3 4]
 [4 5 6]
 [6 7 8]]

[[2 3 4]
 [4 5 6]
 [6 7 8]]
