In [1]:
import array

L = list(range(10))
A = array.array("i", L)
print(f"L:", L)
print(f"A:", A)

L: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
A: array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [6]:
import numpy as np

np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [7]:
np.array([3.14, 4, 2, 3])  # python upcasts if possible when types do not match

array([ 3.14,  4.  ,  2.  ,  3.  ])

In [8]:
np.array([1, 2, 3, 4], dtype="float32")

array([ 1.,  2.,  3.,  4.], dtype=float32)

In [9]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [5]:
import numpy as np

np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
np.ones((3, 5), dtype="float")

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [11]:
np.full((3, 5), 3.14)

array([[ 3.14,  3.14,  3.14,  3.14,  3.14],
       [ 3.14,  3.14,  3.14,  3.14,  3.14],
       [ 3.14,  3.14,  3.14,  3.14,  3.14]])

In [12]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [13]:
np.linspace(0, 1, 5)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ])

In [15]:
np.random.random((3, 3))

array([[ 0.85296888,  0.43556497,  0.04412798],
       [ 0.55791842,  0.48693298,  0.07115575],
       [ 0.10768842,  0.01145473,  0.1548723 ]])

In [16]:
# create a 3x3 array of normally distributed random values with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[-1.64211998,  1.2102595 ,  1.13388717],
       [-0.60263457, -0.6270278 ,  0.57570003],
       [-0.01368519,  0.28587877,  1.30416292]])

In [17]:
np.random.randint(0, 10, (3, 3))  # create a 3x3 array of random integers in the interval (0, 10)

array([[8, 4, 1],
       [4, 8, 0],
       [9, 1, 3]])

In [19]:
# 3x3 identity matrix
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [20]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that memory location
np.empty(3)

array([ 1.,  1.,  1.])

In [21]:
np.zeros(10, dtype="int16")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [22]:
np.zeros(10, dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [8]:
import numpy as np

np.random.seed(0)  # seed for reproducibility same as random.seed(1)
x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3, 4))
x3 = np.random.randint(10, size=(3, 4, 5))

print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)
print()
print("dtype:", x3.dtype)
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60

dtype: int32
itemsize: 4 bytes
nbytes: 240 bytes


In [9]:
x1

array([5, 0, 3, 3, 7, 9])

In [10]:
print("x1[0]:", x1[0])
print("x1[4]:", x1[4])
print("x1[-1]:", x1[-1])
print("x1[-2]:", x1[-2])

x1[0]: 5
x1[4]: 7
x1[-1]: 9
x1[-2]: 7


In [11]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [13]:
# in multidimentional array, we access items using comma-separated tuple of indices
x2[0, 0]  # not x2[(0, 0)]

3

In [15]:
print("x2[2, 0]:", x2[2, 0])
print("x2[2, -1]:", x2[2, -1])

x2[2, 0]: 1
x2[2, -1]: 7


In [16]:
x2[0, 0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [17]:
x1[0] = 3.14159  # NumPy truncates float numbers
x1

array([3, 0, 3, 3, 7, 9])

### NumPy slicing syntax follows standard Python slicing syntax
x[start:stop:step]

In [3]:
import numpy as np

x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
x[:5]

array([0, 1, 2, 3, 4])

In [4]:
x[5:]

array([5, 6, 7, 8, 9])

In [5]:
x[4:7]

array([4, 5, 6])

In [6]:
x[::2]

array([0, 2, 4, 6, 8])

In [7]:
x[1::2]

array([1, 3, 5, 7, 9])

In [8]:
# when step value is negative, the defaults for start and stop are swapped
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [9]:
x[5::-2]

array([5, 3, 1])

### Multidimentionsal array slices

In [10]:
x2 = np.random.randint(10, size=(3, 4))
x2

array([[3, 6, 7, 3],
       [3, 1, 3, 7],
       [8, 4, 8, 7]])

In [11]:
x2[:2, :3]  # two rows, three columns

array([[3, 6, 7],
       [3, 1, 3]])

In [12]:
x2[::-1, ::-1]

array([[7, 8, 4, 8],
       [7, 3, 1, 3],
       [3, 7, 6, 3]])

In [15]:
print(x2[:, 0])  # first column of array x2
print(x2[0, :])  # first row of array x2
print(x2[0])   # more compact way of row access

[3 3 8]
[3 6 7 3]
[3 6 7 3]


### Sub-arrays as no-copy views
## in NumPy arrays, slices provide views sub-arrays, do not create a copy

In [16]:
print(x2)

[[3 6 7 3]
 [3 1 3 7]
 [8 4 8 7]]


In [17]:
# extract 2x2 array
x2_sub = x2[:2, :2]
print(x2_sub)

[[3 6]
 [3 1]]


In [19]:
# modify the sub-array
x2_sub[0, 0] = 99
print(x2_sub)
print()
print(x2)  # original array is changed

[[99  6]
 [ 3  1]]

[[99  6  7  3]
 [ 3  1  3  7]
 [ 8  4  8  7]]
